name: First Workflow CI
on : [push]

jobs: 
    first-job:
        runs-on: ubuntu-latest
        steps:
          - name: echo a sentence
            run: echo 'Hello Mano'
          - name: check versions
            run : |
              node -v
              npm -v
